name: List All PRs
on:
  workflow_dispatch:
jobs:
  list-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List PRs
        uses: ShivamHS/PR-listing@v1.1.4
        with:
          GITHUB_OWNER: 'ShivamHS'
          GITHUB_REPO: 'github-action-demo'
          INPUT_GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}  '
          INPUT_GITHUB_BRANCH: 'main'

      - name: Upload CSV
        uses: action/upload-artifact@v2
        with:
          name: PR_CSV_Report
          path: ${{ steps.pr-report.outputs.csv_file }}
