name: List All PRs
on:
  workflow_dispatch:
jobs:
  list-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List PRs
        uses: ShivamHS/PR-listing@v1.1.10
        with:
          GITHUB_OWNER: 'ShivamHS'
          GITHUB_REPO: 'github-action-demo'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}  '
          GITHUB_BRANCH: 'main'

      - name: path check
        run: |
          cd ${{ secrets.GITHUB_WORKSPACE }}
          ls

      - name: Upload CSV
        uses: actions/upload-artifact@v2
        with:
          name: PR_CSV_Report
          path: ${{ secrets.GITHUB_WORKSPACE }}
