name: List-PRs
on:
  workflow_dispatch
jobs:
  job_name:
    name: List All PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List PR
        uses: ShivamHS/PR-listing@v1.1.1
        with:
          repo_token: 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
          owner: ShivamHS
          repo_name: github-action-demo
          base_branch: main
