name: List-PRs
on:
  workflow_dispatch
jobs:
  job_name:
    name: List All PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List PR
        uses: ShivamHS/PR-listing@v1.1.2
        with:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ShivamHS
          GITHUB_REPO: github-action-demo
          INPUT_GITHUB_BRANCH: main
