name: Delete Tag

on:
  workflow_dispatch:
    inputs:
      Keyword:  
        type: string
        required: true
      delete-type:
        type: string
        required: true
      
      

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute Delete Release/Tag action
        uses: ShivamHS/delete-tag@v1
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repo:  github-action-demo
          owner: ShivamHS
          keyword: " ${{ inputs.Keyword }} "
          deletetype: "tr"
