name: FTP-Connect

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

   # env:
    #  Solution_Name: your-solution-name                         # Replace with your solution name, i.e. MyWpfApp.sln.
     # Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      #Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      #Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        


    - name: FTP Interactions
      uses: priradev/ftp-interactions@v0.2.9-beta
      with:
    # Address for the FTP host.
       host: ftp://waws-prod-blu-253.ftp.azurewebsites.windows.net/site/wwwroot
    # Port for the FTP host.
     
    # Username for the FTP host.
       username: ietestang\$ietestang
    # Password for the FTP host.
       password: AQLFNfUlCq29SLCD8eUAfYCtAytzsgE.fSGbpbctjdX7zl1gJzX52f-VtI3Or7uiiJYkQzUMJGY

    - name: ftp-action
  # You may pin to the exact commit or the version.
  # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
    # FTP host
        host: ftp://waws-prod-blu-253.ftp.azurewebsites.windows.net/site/wwwroot
    # FTP user
        user: ietestang\$ietestang
    # FTP password
        password: AQLFNfUlCq29SLCD8eUAfYCtAytzsgE.fSGbpbctjdX7zl1gJzX52f-VtI3Or7uiiJYkQzUMJGY

       

          
