name: resuable workfow

on:
  workflow_dispatch:

jobs:
  Reusable_Workflow:
    runs-on: Ubuntu-Latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: HenrySchein-C/GEPAngular
        token: ${{ secrets.SECRET_GITHUB }}
        ref: uk_dev

      name: check file
    - run: |
        pwd
        ls 
