name:  Naming Convention
on:
 pull_request:
   types:
     - opened
     - synchronize
jobs:
 enforce-naming:
   runs-on: ubuntu-latest
   steps:
     - name: Check if Target Branch is main
       run: |
         target_branch=${{ github.event.pull_request.base.ref }}
         if [[ $target_branch != "main" ]]; then
           echo "Skipping checks as the target branch is not 'sprint'."
           exit 0
         fi
     - name: Check Branch Name
       run: |
         branch_name=${{ github.event.pull_request.head.ref }}
         if [[ ! $branch_name =~ ^GEP/CR-|bug-|feature-[A-Z]+\d+$ ]]; then
           echo "Branch name does not match the required pattern."
           exit 1
         fi
     - name: Check PR Title
       run: |
         pr_title=${{ github.event.pull_request.title }}
         if [[ ! $pr_title =~ ^[A-Z][a-z0-9_-]+\s#[0-9]+$ ]]; then
           echo "PR title does not match the required format."
           exit 1
         fi
