name: Naming Convention
on:
 pull_request:
   types:
     - opened
     - synchronize
jobs:
 enforce-naming:
   runs-on: ubuntu-latest
   steps:
     - name: Check Branch Name
       run: |
         branch_name=${{ github.event.pull_request.head.ref }}
         if [[ ! $branch_name =~ ^[a-z]+/[a-z]+/[a-z0-9_-]+$ ]]; then
           echo "Branch name does not match the required pattern."
           exit 1
         fi
     - name: Check PR Title
       run: |
         pr_title=${{ github.event.pull_request.title }}
         if [[ ! $pr_title =~ ^[A-Z][a-z0-9_-]+\s#[0-9]+$ ]]; then
           echo "PR title does not match the required format."
           exit 1
         fi
