name: PR Nomencleture
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
 pr-title-check:
   runs-on: windows-latest
   steps:
   - name: Check PR title format
     uses: actions/checkout@v2
   - name: Check PR title
     id: check_pr_title
     run: |
       $prTitle = "${{ github.event.pull_request.title }}"
       $regexPattern = "GEP/\d+/[a-zA-Z0-9_]+"
       if ($prTitle -notmatch $regexPattern) {
         Write-Output "PR title does not match the required format. Please use 'GEP/JIRA-ID/feature-name' format."
         exit 1
       }
   - name: Set PR status check
     if: ${{ steps.check_pr_title.outcome == 'failure' }}
     run: |
       echo "The PR title does not match the required format. Please update the title and try again."
       echo "::error::PR title does not match the required format."
       exit 1
