name: PR Nomencleture
on:
 pull_request:
   types: [opened, edited]
jobs:
 pr-title-check:
   runs-on: ubuntu-latest
   steps:
   - name: Check PR title format
     uses: actions/checkout@v2
   - name: Install PowerShell
     uses: actions/setup-powershell@v1
     with:
       pwsh-version: '7.1'
   - name: Check PR title
     id: check_pr_title
     run: |
       $prTitle = "${{ github.event.pull_request.title }}"
       $regexPattern = "^GEP/[A-Z]+-\d+/.+"
       if ($prTitle -notmatch $regexPattern) {
         Write-Output "PR title does not match the required format. Please use 'GEP/JIRA-ID/feature-name' format."
         exit 1
       }
   - name: Set PR status check
     if: ${{ steps.check_pr_title.outcome == 'failure' }}
     run: |
       echo "The PR title does not match the required format. Please update the title and try again."
       echo "::set-output name=status::failure"
 # Add more jobs for other checks or actions required by your workflow
# Mark the status check as successful if all checks pass
 status_check:
   runs-on: ubuntu-latest
   needs: [pr-title-check]  # Add other jobs as needed
   steps:
     - name: Set PR status
       if: ${{ needs.pr-title-check.outputs.status != 'failure' }}
       run: echo "All checks passed"
