name: 'PR Nomencleture'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: dekinderfiets/pr-name-enforcer@0.0.1
      with:
    # The GITHUB_TOKEN secret
       repo-token: ${{ secrets.GITHUB_TOKEN }}
    # The regex
       regex: ^(?!\\s?[A-Z]).+$
    # Optional error message when match failed
       error-message: Change PR
          
     
