name: "Publish"

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@main"
      - name: Publish to PSGallery
        uses: jcwillox/action-publish-powershell-script@main
        with:
          path: myscript.ps1
          nuget_api_key: ${{ secrets.PSGALLERY_KEY }}
          # you can use an alternate name if the scripts name is taken
          name: alternate-name
