name: Sitemap

on:
  workflow_dispatch:


env:
  AZURE_WEBAPP_PACKAGE_PATH: 'dist'
  OUTPUT_FOLDER_PATH: './output'

jobs:
 CDArtifact:
   runs-on: windows-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v2
   - name: Download files from Azure Storage
     run: |
           echo ${{ github.workspace }}
           $username = "`$mc-045a2475-f692-42d4-a7c0-9647-cm"
           $password = "hj7FlxetnWDJiXwDbehP2KWWLYnpZ3WYjSHh0eFgwa1vve5Y0ds7zsE1gPxq"
           $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username,$password)))
           $userAgent = "powershell/1.0"
           $apiUrl = "https://mc-045a2475-f692-42d4-a7c0-9647-cm.scm.azurewebsites.net:443/api/zip/site/wwwroot/App_Data/Sitemap/HenryScheinIE/"

           $filePath = "${{ github.workspace }}/dist.zip"
           Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -UserAgent $userAgent -Method GET -OutFile $filePath -ContentType "multipart/form-data"
           

           
   - name: Archive CMS artifacts
     uses: actions/upload-artifact@v3
     with:
          name: dist
          retention-days: 15
          path: ${{ github.workspace }}/dist.zip

 ArtifactToNode:
  runs-on: ubuntu-latest
  needs: [CDArtifact, SAtoNode]
  steps:

    - name: Create folder
      run: |
        pwd
        ls -lrth
  
    - name: Downloading build files
      uses: actions/download-artifact@v3
      with:
        name: dist

    - name: Downloading build files
      uses: actions/download-artifact@v3
      with:
        name: dist_sa

    - name: List files
      run: |
            pwd
            ls -lrth

    - name: Extract files
      run: |
        unzip -o dist.zip
        ls
        mkdir dist
        mv /home/runner/work/github-action-demo/github-action-demo/*.xml /home/runner/work/github-action-demo/github-action-demo/dist/
  

    - name: Final Check of folder
      run: |
        cd dist
        ls -lrth

        


    - name: Create folder
      run: |
          mkdir ${{ env.OUTPUT_FOLDER_PATH }}
          cp -R ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} ${{ env.OUTPUT_FOLDER_PATH }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/
          rm -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/*
          mkdir ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          cp -R ${{ env.OUTPUT_FOLDER_PATH }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/
       
    - name: Deloy to Web App
      uses: azure/webapps-deploy@v2
      with:
       app-name: ietestang
       publish-profile: ${{ secrets.IETESTANGCRED }}
       package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


 SAtoNode:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v2
   - name: Download files from Azure Storage
     run: |
        mkdir dist
        blob_list=$(az storage blob list --account-name hsdevstorageaccount --account-key ${{ secrets.SA_KEY_DEV }} --container-name sitemap --output json --prefix henryschein-ie/)
        for blob_name in $(echo "$blob_list" | jq -r '.[].name'); do
          if [ "$blob_name" != "henryschein-ie/DoNotDelete.txt" ]; then
            file_name=$(basename "$blob_name")
            az storage blob download --account-name hsdevstorageaccount --account-key ${{ secrets.SA_KEY_DEV }} --container-name sitemap --name "$blob_name" --file "./dist/$file_name"
          fi
        done
  
   - name: Archive CMS artifacts
     uses: actions/upload-artifact@v3
     with:
          name: dist_sa
          retention-days: 15
          path: dist

